# Generated by Django 3.1 on 2020-11-08 15:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='major',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default='', max_length=150, verbose_name='degree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='publicity',
            field=models.BooleanField(default=False, verbose_name='publicity'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname_display',
            field=models.CharField(blank=True, choices=[('none', 'Regular'), ('quotes', 'Quotes'), ('brackets', 'Brackets')], max_length=1000, verbose_name='nickname_display'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='work',
            name='publicity',
            field=models.BooleanField(default=False, verbose_name='publicity'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.IntegerField(blank=True, verbose_name='end year'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.IntegerField(blank=True, verbose_name='end year'),
        ),
    ]
