# Generated by Django 3.1 on 2020-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
