# Generated by Django 3.1 on 2020-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('done', 'Done'), ('working_on_it', 'Working on it'), ('stuck', 'Stuck'), ('not_started', 'Not Started')], default='not_started', max_length=13)),
                ('intensity', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('demon', 'Demon'), ('unrated', 'Unrated')], default='unrated', max_length=7)),
                ('notes', models.TextField(blank=True, max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_on', models.DateField()),
            ],
        ),
    ]
