# Generated by Django 3.1 on 2020-09-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoSubitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('source', models.CharField(blank=True, max_length=30, verbose_name='Source')),
                ('status', models.CharField(choices=[('done', 'Done'), ('in progress', 'In Progress'), ('stuck', 'Stuck'), ('not started', 'Not Started')], max_length=20, verbose_name='status')),
                ('intensity', models.CharField(choices=[('demon', 'Demon'), ('normal', 'Normal'), ('easy', 'Easy'), ('unrated', 'Unrated')], max_length=20, verbose_name='intensity')),
                ('notes', models.TextField(blank=True, max_length=120, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('source', models.CharField(blank=True, max_length=30, verbose_name='Source')),
                ('status', models.CharField(choices=[('done', 'Done'), ('in progress', 'In Progress'), ('stuck', 'Stuck'), ('not started', 'Not Started')], max_length=20, verbose_name='status')),
                ('intensity', models.CharField(choices=[('demon', 'Demon'), ('normal', 'Normal'), ('easy', 'Easy'), ('unrated', 'Unrated')], max_length=20, verbose_name='intensity')),
                ('notes', models.TextField(blank=True, max_length=120, verbose_name='Notes')),
                ('due_date', models.DateField(auto_now_add=True, verbose_name='Due Date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('subitems', models.ManyToManyField(blank=True, null=True, related_name='Subitems', to='todos.TodoSubitem')),
            ],
        ),
    ]
