# Generated by Django 3.1 on 2020-11-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('starred', models.BooleanField(default=False, verbose_name='starred')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('source', models.CharField(blank=True, max_length=20, verbose_name='source')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='description')),
                ('status', models.CharField(blank=True, choices=[('done', 'Done'), ('working', 'In Progress'), ('stuck', 'Stuck'), ('none', 'Not Started')], max_length=10, verbose_name='status')),
                ('date', models.DateField(blank=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='description')),
                ('favorite', models.BooleanField(default=False, verbose_name='favorite')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('collapse', models.BooleanField(default=False, verbose_name='collapse')),
                ('color', models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('grey', 'Grey')], max_length=10, verbose_name='color')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.board')),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='description')),
                ('status', models.CharField(blank=True, choices=[('done', 'Done'), ('working', 'In Progress'), ('stuck', 'Stuck'), ('none', 'Not Started')], max_length=10, verbose_name='status')),
                ('date', models.DateField(blank=True, verbose_name='date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.table'),
        ),
        migrations.AddField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.workspace'),
        ),
    ]
